name: Build ipobfs binary for ramips/mt7621

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDK_URL: https://archive.openwrt.org/releases/24.10.2/targets/ramips/mt7621/openwrt-sdk-24.10.2-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst
      SDK_DIR: ${{ github.workspace }}/openwrt-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion python3 unzip wget zstd

    - name: Download and extract OpenWRT SDK
      run: |
        wget $SDK_URL -O sdk.tar.zst
        mkdir -p $SDK_DIR
        tar -I zstd -xf sdk.tar.zst -C $SDK_DIR
        SDK_PATH=$(tar -tf sdk.tar.zst | head -n 1 | cut -f1 -d"/")
        mv $SDK_DIR/$SDK_PATH/* $SDK_DIR

    - name: Prepare SDK environment
      run: |
        cd $SDK_DIR
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy ipobfs sources to SDK
      run: |
        mkdir -p $SDK_DIR/package/ipobfs
        cp -r ipobfs/* $SDK_DIR/package/ipobfs/
        cp -r ipobfs_mod $SDK_DIR/package/ipobfs/

    - name: Build ipobfs binary
      run: |
        cd $SDK_DIR
        make package/ipobfs/compile V=99
        find bin/targets -type f -executable -name ipobfs -exec cp {} $GITHUB_WORKSPACE/ipobfs \;

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipobfs-binary
        path: ipobfs
