name: Build ipobfs for amd64 and arm64

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cross build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu libnetfilter-queue-dev libnfnetlink-dev libcap-dev
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
            echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          else
            export CC=gcc
            echo "CC=gcc" >> $GITHUB_ENV
          fi

      - name: Build project
        working-directory: ./ipobfs
        run: make

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipobfs-${{ matrix.arch }}
          path: ipobfs/ipobfs
