name: Build ipobfs (multi-arch)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build inside Docker (for ${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: ./ipobfs
          file: ./ipobfs/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: false
          outputs: type=local,dest=./build-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipobfs-${{ matrix.arch }}
          path: build-${{ matrix.arch }}
